name: CI/CD - Ejecutar pruebas unitarias

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t my-node-app ./app

    - name: Run Docker container
      run: |
        docker run -d -p 8012:8012 --name node-app my-node-app

    - name: Wait for the app to start
      run: |
        while ! curl --silent --fail localhost:8012/test; do
          echo "Waiting for the app to start...";
          sleep 3;
        done

    - name: Run unit tests
      run: |
        docker exec node-app npm test --prefix /app

    - name: Stop Docker container
      run: |
        docker stop node-app
        docker rm node-app
